In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.shape

(6,)

In [4]:
arr2 = arr[np.newaxis, :] # will add new axis as a row, so 1 list with 6 elements
arr2

array([[1, 2, 3, 4, 5, 6]])

In [5]:
arr2.shape

(1, 6)

In [6]:
arr3 = arr[:, np.newaxis] # will add new axis as a column, so 6 lists with 1 element each
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
arr2 = np.expand_dims(arr, axis=0) # Same as arr2 = arr[np.newaxis, :], however more readable
arr2

array([[1, 2, 3, 4, 5, 6]])

In [9]:
arr2.shape

(1, 6)

In [10]:
arr3 = np.expand_dims(arr, axis=1) # Same as arr3 = arr[:, np.newaxis]; however more readable
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
arr3.shape

(6, 1)