In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arr = np.array([1,2,3,4], dtype='str')
arr

array(['1', '2', '3', '4'], dtype='<U1')

In [4]:
arr = np.array([1,2,3,4], dtype='int8')
arr

array([1, 2, 3, 4], dtype=int8)

In [6]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [7]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [8]:
empty = np.empty(5)
empty

array([1., 1., 1., 1., 1.])

In [10]:
my_range = np.arange(5)
my_range

array([0, 1, 2, 3, 4])

In [11]:
arr = np.arange(2, 10, 2)
arr

array([2, 4, 6, 8])

In [14]:
arr = np.linspace(0, 10, num=3)
arr

array([ 0.,  5., 10.])