In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30])
arr

array([10, 20, 30])

In [3]:
arr * .5

array([ 5., 10., 15.])

In [9]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([2,3,4])

arr1 * arr2

array([ 20,  60, 120])

In [10]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([2])

arr1 * arr2

array([20, 40, 60])

In [11]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([2,3,])

arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 