In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
new_arr = arr[3:6]
new_arr

array([3, 4, 5])

In [4]:
arr1 = [[1,1], [2,2]]
arr2 = [[3,3], [4,4]]

print('arr1:', arr1)
print('arr2:', arr2)

arr1: [[1, 1], [2, 2]]
arr2: [[3, 3], [4, 4]]


In [5]:
np.vstack((arr1, arr2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [6]:
np.hstack((arr1, arr2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [7]:
arr = np.arange(1, 13).reshape(2, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
np.hsplit(arr, 3)

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [11]:
original = np.arange(10)
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
new_arr = original[3:6]
new_arr

array([3, 4, 5])

In [13]:
new_arr[0] = 999
new_arr

array([999,   4,   5])

In [18]:
original_2 = np.arange(10)

In [19]:
new_arr = original_2.copy()
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
new_arr[5] = 999
new_arr

array([  0,   1,   2,   3,   4, 999,   6,   7,   8,   9])

In [21]:
original_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])