In [1]:
import numpy as np

In [2]:
arr = np.array([1,9,9,2,1,2,2,3,4,5,7])

In [3]:
np.unique(arr)

array([1, 2, 3, 4, 5, 7, 9])

In [4]:
np.unique(arr, return_index=True)

(array([1, 2, 3, 4, 5, 7, 9]), array([ 0,  3,  7,  8,  9, 10,  1]))

In [5]:
np.unique(arr, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 7, 9]),
 array([ 0,  3,  7,  8,  9, 10,  1]),
 array([2, 3, 1, 1, 1, 1, 2]))

In [7]:
arr = np.array([[1,1,2],
               [3,3,4],
              [1,1,2]])

arr

array([[1, 1, 2],
       [3, 3, 4],
       [1, 1, 2]])

In [8]:
np.unique(arr)

array([1, 2, 3, 4])

In [9]:
np.unique(arr, axis=0)

array([[1, 1, 2],
       [3, 3, 4]])

In [10]:
np.unique(arr, axis=1)

array([[1, 2],
       [3, 4],
       [1, 2]])