In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
arr[arr > 5]

array([6, 7, 8, 9])

In [9]:
even_numbers = arr[arr % 2 == 0]
arr[even_numbers]

array([0, 2, 4, 6, 8])

In [10]:
even_numbers = (arr % 2 == 0) & (arr != 0)
arr[even_numbers]

array([2, 4, 6, 8])

In [11]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
mask = np.nonzero(arr > 5)
mask

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [13]:
arr[mask]

array([ 6,  7,  8,  9, 10, 11, 12])