In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
arr[1:3]

array([[3, 4],
       [5, 6]])

In [4]:
arr[2][0] # Accessing the first element from the 3rd list

np.int64(5)

In [5]:
arr.sum()

np.int64(21)

In [6]:
arr.mean()

np.float64(3.5)

In [7]:
arr.max()

np.int64(6)

In [8]:
arr.min()

np.int64(1)

In [9]:
arr.max(axis=1)

array([2, 4, 6])

In [10]:
arr.max(axis=0)

array([5, 6])

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [14]:
new_row = np.array([10])
arr * new_row

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
rng = np.random.default_rng()
rng.random(5)

array([0.87293566, 0.62846656, 0.09185972, 0.80187152, 0.42065074])

In [17]:
rng.random((4, 2))

array([[0.54694555, 0.51663803],
       [0.87126139, 0.33736963],
       [0.28838491, 0.32582272],
       [0.91373428, 0.33661572]])