In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [5]:
arr[0]

array([1, 2])

In [6]:
arr[0][1]

np.int64(2)

In [7]:
arr[-1]

array([3, 4])