In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x1BFEEBA9620

In [3]:
rng.integers(low=1, high=5, size=(3,4)) # high= parameter is exclusive by default

array([[1, 2, 4, 3],
       [1, 1, 4, 4],
       [1, 4, 3, 1]])

In [4]:
rng.integers(low=1, high=50, size=(3,4), endpoint=True) # Makes high number inclusive

array([[11, 31, 38, 27],
       [13, 34, 34, 17],
       [10, 47, 41, 10]])

In [7]:
rng.random(size=(2, 3, 4))

array([[[0.86381792, 0.9847359 , 0.46732625, 0.25279556],
        [0.70603564, 0.13613299, 0.09834264, 0.06666866],
        [0.18212339, 0.09721594, 0.91003955, 0.58191107]],

       [[0.21829183, 0.3776142 , 0.36477984, 0.65183052],
        [0.64819992, 0.66623798, 0.47227512, 0.25419902],
        [0.24940957, 0.77809936, 0.83876998, 0.86026386]]])