In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
flattened = arr.flatten()
flattened[0] = 10 # changing the element at index 0 to number 10
flattened

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
flattened = arr.ravel()
flattened[0] = 10 # changing the element at index 0 to number 10
flattened

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
arr

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])