In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr.reshape(4, 2) # Reshape it into 4 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [5]:
arr.transpose().transpose() # using the method second time, will reverse it back

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])