In [1]:
import numpy as np

In [6]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
np.flip(arr)

array([5, 4, 3, 2, 1, 0])

In [8]:
arr[::-1]

array([5, 4, 3, 2, 1, 0])

In [9]:
arr = np.array([[1,2,3],
                [4,5,6], 
                [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.flip(arr) # will reverse from top to bottom, from left to right

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [11]:
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [18]:
np.flip(arr, axis=0) # same as using slicing [::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [13]:
np.flip(arr, axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [17]:
np.flip(arr[0]) # reverses a single row at the index of 0

array([3, 2, 1])

In [16]:
np.flip(arr[:, 2]) # reverses a single column at the index of 2

array([9, 6, 3])