In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4,5,6],
               [7,8,9,10,11,12]])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [3]:
np.save('my_array.npy', arr) # Will save with the specified name, in this folder

In [4]:
np.load('my_array.npy')

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
my_array1 = np.array([1, 2, 3])
my_array2 = np.array([[4, 5], [6, 7]])

In [8]:
np.savez('multiple_arrays.npz', array1=my_array1, array2=my_array2 )

In [12]:
loaded = np.load('multiple_arrays.npz)

array([[4, 5],
       [6, 7]])

In [13]:
loaded['array1']

array([1, 2, 3])

In [14]:
loaded['array2']

array([[4, 5],
       [6, 7]])

In [16]:
np.savetxt('text_array.txt', arr)

In [17]:
np.loadtxt('text_array.csv')

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

In [18]:
np.loadtxt('text_array.txt')

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])