In [1]:
import numpy as np

In [2]:
np.sort([20,18,16,33,5,1,3,4,2,6,9,8,7,4,1,2,5,69,98])

array([ 1,  1,  2,  2,  3,  4,  4,  5,  5,  6,  7,  8,  9, 16, 18, 20, 33,
       69, 98])

In [3]:
arr_a = np.array([1,2,3,4])
arr_b = np.array([5,6,7,8])

np.concatenate((arr_a, arr_b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr_a = np.array([[1,2],[3,4]])
arr_b = np.array([[5,6],[7,8]])

np.concatenate((arr_a, arr_b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
arr_a = np.array([[1,2],[3,4]])
arr_b = np.array([[5,6],[7,8]])

np.concatenate((arr_a, arr_b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])